app = "solar-dinoweb"
primary_region = "fra"

[build]
  builder = "nixpacks"

[env]
  UPLOAD_DIR = "/tmp/elaborazioni"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
