# fly.toml app configuration file for solar-dinoweb
app = 'solar-dinoweb'
primary_region = 'fra'

[build]
  dockerfile = "Dockerfile"

[env]
  UPLOAD_DIR = '/tmp/elaborazioni'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

# Ho rimosso la sezione [[http_service.checks]] per assicurarci 
# che Fly.io mandi il traffico al dominio senza errori di "Health Check".